[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyIterative"
version = "0.1.0"
description = "A package for iterative clustering based on CONCORD and weighted t-tests."
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
authors = [
    {name = "Michael J. Deines", email = "deines@purdue.edu"}
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
]

dependencies = [
    "scanpy",
    "pandas>=1.5.0,<2.0.0",
    "igraph",
    "leidenalg",
    "numpy>=1.24.0,<2.0.0",
    "scipy>=1.7.0",
    "statsmodels>=0.13.0",
    "concord-sc",
    "torch>=2.0.0",
    "pynndescent>=0.5.6",
    "tqdm>=4.60.0",
    "scikit-learn>=1.5.0",
    "joblib>=1.5.0"
]

[tool.setuptools]
packages = ["pyiterative"]
